version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-owncloud:
    image: owncloud:9.1.4-apache
    container_name:  §§INSTANCE-owncloud
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-owncloud-db:owncloud-db
    ports:
      - "80"
    depends_on:
      - §§INSTANCE-owncloud-db
    volumes:
      - ./data/data:/var/www/html/data
      - ./data/apps:/var/www/html/apps
      - ./configs:/var/www/html/config

  §§INSTANCE-owncloud-db:
    image: mariadb
    container_name: §§INSTANCE-owncloud-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
    volumes: 
      - ./data/mysql:/var/lib/mysql
